export const SIGN_IN = "SIGN_IN";
export const SIGN_UP = "SIGN_UP";
export const REGISTER = "REGISTER";
export const LOG_OUT = "LOG_OUT";
export const AUTO_LOGIN = "AUTO_LOGIN";

export const GET_PROFILE = "GET_PROFILE";
export const GET_PROFILE_AUTH_USER = "GET_PROFILE_AUTH_USER";
export const GET_PROFILE_SKILLS = "GET_PROFILE_SKILLS";
export const GET_PROFILE_WORK_EXPERIENCE = "GET_PROFILE_WORK_EXPERIENCE";
export const GET_PROFILE_EDUCATION = "GET_PROFILE_EDUCATION";
export const GET_PROFILE_POSTS = "GET_PROFILE_POSTS";
export const GET_PUBLIC_PROFILES = "GET_PUBLIC_PROFILES";
export const SEARCH_PUBLIC_PROFILES = "SEARCH_PUBLIC_PROFILES";
export const GET_NOT_BLOCKED_PROFILES = "GET_NOT_BLOCKED_PROFILES";
export const SEARCH_NOT_BLOCKED_PROFILES = "SEARCH_NOT_BLOCKED_PROFILES";
export const LINK_WITH_PROFILE = "LINK_WITH_PROFILE";
export const DISLINK_WITH_PROFILE = "DISLINK_WITH_PROFILE";
export const BLOCK_PROFILE = "BLOCK_PROFILE";
export const SAVE_PROFILE = "SAVE_PROFILE";
export const ADD_SKILL = "ADD_SKILL";
export const DELETE_SKILL = "DELETE_SKILL";
export const ADD_WORK_EXPERIENCE = "ADD_WORK_EXPERIENCE";
export const DELETE_WORK_EXPERIENCE = "DELETE_WORK_EXPERIENCE";
export const ADD_EDUCATION = "ADD_EDUCATION";
export const DELETE_EDUCATION = "DELETE_EDUCATION";
export const GET_CONNECTION_REQUESTS = "GET_CONNECTION_REQUESTS";
export const ACCEPT_CONNECTION_REQUEST = "ACCEPT_CONNECTION_REQUEST";
export const DECLINE_CONNECTION_REQUEST = "DECLINE_CONNECTION_REQUEST";

export const GET_POSTS = "GET_POSTS";
export const SEARCH_POSTS = "SEARCH_POSTS";
export const CREATE_COMMENT = "CREATE_COMMENT";
export const REACT_TO_POST = "REACT_TO_POST";
export const ADD_POST = "ADD_POST";

export const GET_JOB_OFFERS = "GET_JOB_OFFERS";
export const SEARCH_JOB_OFFERS = "SEARCH_JOB_OFFERS";
export const ADD_JOB_OFFER = "ADD_JOB_OFFER";

export const GET_NOTIFICATIONS = "GET_NOTIFICATIONS";
export const UPDATE_NOTIFICATIONS = "UPDATE_NOTIFICATIONS";
