import { all, takeLatest } from "redux-saga/effects";
import {
  ACCEPT_CONNECTION_REQUEST,
  ADD_EDUCATION,
  ADD_JOB_OFFER,
  ADD_POST,
  ADD_SKILL,
  ADD_WORK_EXPERIENCE,
  AUTO_LOGIN,
  BLOCK_PROFILE,
  CREATE_COMMENT,
  DECLINE_CONNECTION_REQUEST,
  DELETE_EDUCATION,
  DELETE_SKILL,
  DELETE_WORK_EXPERIENCE,
  DISLINK_WITH_PROFILE,
  GET_CONNECTION_REQUESTS,
  GET_JOB_OFFERS,
  GET_NOTIFICATIONS,
  GET_NOT_BLOCKED_PROFILES,
  GET_POSTS,
  GET_PROFILE,
  GET_PROFILE_AUTH_USER,
  GET_PROFILE_EDUCATION,
  GET_PROFILE_POSTS,
  GET_PROFILE_SKILLS,
  GET_PROFILE_WORK_EXPERIENCE,
  GET_PUBLIC_PROFILES,
  LINK_WITH_PROFILE,
  LOG_OUT,
  REACT_TO_POST,
  REGISTER,
  SAVE_PROFILE,
  SEARCH_JOB_OFFERS,
  SEARCH_NOT_BLOCKED_PROFILES,
  SEARCH_POSTS,
  SEARCH_PUBLIC_PROFILES,
  SIGN_IN,
  SIGN_UP,
  UPDATE_NOTIFICATIONS,
} from "../actions/action-types";
import {
  handleAutoLogin,
  handleLogOut,
  handleRegister,
  handleSignIn,
  handleSignUp,
} from "./auth-saga";
import {
  handleAddJobOffer,
  handleGetJobOffers,
  handleSearchJobOffers,
} from "./job-offer-saga";
import {
  handleGetNotifications,
  handleUpdateNotifications,
} from "./notifications-saga";
import {
  handleAddPost,
  handleCreateComment,
  handleGetPosts,
  handleGetProfilePosts,
  handleReactToPost,
  handleSearchPosts,
} from "./post-saga";
import {
  handleAcceptConnectionRequest,
  handleAddEducation,
  handleAddSkill,
  handleAddWorkExperience,
  handleBlockProfile,
  handleDeclineConnectionRequest,
  handleDeleteEducation,
  handleDeleteSkill,
  handleDeleteWorkExperience,
  handleDislinkWithProfile,
  handleGetConnectionRequests,
  handleGetNotBlockedProfiles,
  handleGetProfile,
  handleGetProfileAuthUser,
  handleGetProfileEducation,
  handleGetProfileSkills,
  handleGetProfileWorkExperience,
  handleGetPublicProfiles,
  handleLinkWithProfile,
  handleSaveProfile,
  handleSearchNotBlockedProfiles,
  handleSearchPublicProfiles,
} from "./profile-saga";

export default function* rootSaga() {
  yield all([
    takeLatest(SIGN_IN, handleSignIn),
    takeLatest(SIGN_UP, handleSignUp),
    takeLatest(REGISTER, handleRegister),
    takeLatest(LOG_OUT, handleLogOut),
    takeLatest(AUTO_LOGIN, handleAutoLogin),
    takeLatest(GET_PROFILE, handleGetProfile),
    takeLatest(GET_PROFILE_AUTH_USER, handleGetProfileAuthUser),
    takeLatest(GET_PROFILE_SKILLS, handleGetProfileSkills),
    takeLatest(GET_PROFILE_WORK_EXPERIENCE, handleGetProfileWorkExperience),
    takeLatest(GET_PROFILE_EDUCATION, handleGetProfileEducation),
    takeLatest(GET_PROFILE_POSTS, handleGetProfilePosts),
    takeLatest(GET_PUBLIC_PROFILES, handleGetPublicProfiles),
    takeLatest(SEARCH_PUBLIC_PROFILES, handleSearchPublicProfiles),
    takeLatest(GET_NOT_BLOCKED_PROFILES, handleGetNotBlockedProfiles),
    takeLatest(SEARCH_NOT_BLOCKED_PROFILES, handleSearchNotBlockedProfiles),
    takeLatest(GET_POSTS, handleGetPosts),
    takeLatest(SEARCH_POSTS, handleSearchPosts),
    takeLatest(CREATE_COMMENT, handleCreateComment),
    takeLatest(REACT_TO_POST, handleReactToPost),
    takeLatest(LINK_WITH_PROFILE, handleLinkWithProfile),
    takeLatest(DISLINK_WITH_PROFILE, handleDislinkWithProfile),
    takeLatest(BLOCK_PROFILE, handleBlockProfile),
    takeLatest(SAVE_PROFILE, handleSaveProfile),
    takeLatest(ADD_SKILL, handleAddSkill),
    takeLatest(DELETE_SKILL, handleDeleteSkill),
    takeLatest(ADD_WORK_EXPERIENCE, handleAddWorkExperience),
    takeLatest(DELETE_WORK_EXPERIENCE, handleDeleteWorkExperience),
    takeLatest(ADD_EDUCATION, handleAddEducation),
    takeLatest(DELETE_EDUCATION, handleDeleteEducation),
    takeLatest(ADD_POST, handleAddPost),
    takeLatest(GET_JOB_OFFERS, handleGetJobOffers),
    takeLatest(SEARCH_JOB_OFFERS, handleSearchJobOffers),
    takeLatest(ADD_JOB_OFFER, handleAddJobOffer),
    takeLatest(GET_CONNECTION_REQUESTS, handleGetConnectionRequests),
    takeLatest(ACCEPT_CONNECTION_REQUEST, handleAcceptConnectionRequest),
    takeLatest(DECLINE_CONNECTION_REQUEST, handleDeclineConnectionRequest),
    takeLatest(GET_NOTIFICATIONS, handleGetNotifications),
    takeLatest(UPDATE_NOTIFICATIONS, handleUpdateNotifications),
  ]);
}
